### ISSUE TITLE
Validatie geeft

### ISSUE THREAD

**Issue by Theo-denBlanken** [25530/J-Query-Helden#3]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/25530/J-Query-Helden/blob/master/

Feedback: 5 errors[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by 25530** [comment]
Ik ben Sam en de issues zijn opgelost
